import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    position: 'relative',
  },
  homeMergeGradient: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  darkOverlay: {
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  scrollContent: {
    paddingHorizontal: 22,
    paddingTop: 0,
    paddingBottom: 10,
    zIndex: 1,
  },
  topReservedSpace: {
    height: 46,
  },
  bottomReservedSpace: {
    height: 92,
  },
  heroSection: {
    alignItems: 'center',
    marginTop: 6,
    marginBottom: 22,
  },
  flameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  largeFlame: {
    fontSize: 68,
    color: '#80B3FF',
    marginHorizontal: 10,
  },
  sparkle: {
    fontSize: 20,
    color: '#4D8B8D',
    marginTop: -18,
  },
  sparkleRight: {
    fontSize: 20,
    color: '#4D8B8D',
    marginTop: 14,
  },
  heroFlameWrap: {
    width: 150,
    height: 150,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroFlameGif: {
    width: 120,
    height: 120,
  },
  heroFlameBadge: {
    width: 128,
    height: 128,
    borderRadius: 64,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 241, 204, 0.45)',
    borderWidth: 1,
    borderColor: 'rgba(255, 196, 112, 0.45)',
    shadowColor: '#F3A84E',
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  heroFlameEmoji: {
    fontSize: 74,
    lineHeight: 82,
  },
  heroIconOuter: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: '#A7C8F8',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 8,
  },
  heroIconInner: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#EFF6FF',
  },
  daysText: {
    fontSize: 66,
    fontWeight: '800',
    color: '#1A1A1A',
    marginTop: 10,
    lineHeight: 72,
  },
  daysSubtitle: {
    fontSize: 35 / 2,
    color: '#383C42',
    marginBottom: 11,
  },
  currentStreakText: {
    fontSize: 31 / 2,
    color: '#2A2A2A',
    fontWeight: '700',
  },
  currentStreakEmoji: {
    fontSize: 16,
  },
  greenTick: {
    color: '#FF7A2D',
    fontWeight: 'bold',
  },
  streakWidget: {
    backgroundColor: '#FFFEFC',
    borderRadius: 28,
    paddingHorizontal: 18,
    paddingVertical: 18,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#EEE8DD',
    overflow: 'visible',
    position: 'relative',
    zIndex: 2,
  },
  streakAuraCore: {
    position: 'absolute',
    top: -12,
    left: 10,
    right: 10,
    height: 22,
    backgroundColor: '#FFD780',
    opacity: 0.20,
    borderRadius: 18,
  },
  streakAuraMid: {
    position: 'absolute',
    top: -44,
    left: 18,
    right: 18,
    height: 48,
    backgroundColor: '#FFEABB',
    opacity: 0.14,
    borderRadius: 28,
  },
  streakAuraFade: {
    position: 'absolute',
    top: -92,
    left: -6,
    right: -6,
    height: 76,
    backgroundColor: '#FFF6D8',
    opacity: 0.10,
    borderRadius: 38,
  },
  streaksDropdown: {
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: '#D8DEE6',
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 22,
    marginBottom: 18,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  streaksDropdownText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#121417',
  },
  streaksChevron: {
    fontSize: 16,
    color: '#333842',
    marginTop: 1,
  },
  weekHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  weekDateRange: {
    fontSize: 33 / 2,
    color: '#1A1C1E',
    fontWeight: '600',
  },
  arrowControls: {
    flexDirection: 'row',
  },
  arrowBtn: {
    borderWidth: 1,
    borderColor: '#CDD0D8',
    borderRadius: 10,
    padding: 5,
    marginLeft: 5,
    width: 33,
    height: 33,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  arrowText: {
    fontSize: 16,
    color: '#252A33',
    fontWeight: '700',
  },
  weekDays: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  dayColumn: {
    alignItems: 'center',
  },
  dayLabel: {
    fontSize: 14,
    color: '#8C8C8F',
    marginBottom: 10,
    width: 32,
    textAlign: 'center',
  },
  logCard: {
    backgroundColor: '#FFFEFC',
    borderRadius: 28,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#EEE8DD',
  },
  logCardTitle: {
    fontSize: 42 / 2,
    fontWeight: '700',
    color: '#111215',
    marginBottom: 14,
  },
  logTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 14,
  },
  logStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  avatarGroup: {
    flexDirection: 'row',
    marginRight: 10,
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#5B5C60',
    borderWidth: 2,
    borderColor: '#F6F6F7',
  },
  avatarTop: {
    zIndex: 2,
  },
  avatarBack: {
    marginLeft: -10,
    backgroundColor: '#ccc',
    zIndex: 1,
  },
  logStatsText: {
    fontSize: 34 / 2,
    color: '#2B2B2F',
    fontWeight: '500',
  },
  logButton: {
    backgroundColor: '#0A0B0D',
    borderRadius: 28,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#F2A600',
    shadowColor: '#F2A600',
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  logButtonText: {
    color: '#FFFFFF',
    fontSize: 35 / 2,
    fontWeight: '700',
  },
  bottomTabBar: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    flexDirection: 'row',
    backgroundColor: '#F4F4F6',
    justifyContent: 'space-around',
    paddingTop: 12,
    paddingBottom: 20,
    borderTopWidth: 1,
    borderColor: '#E7E7EA',
  },
  tabIcon: {
    width: 58,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabIconText: {
    fontSize: 24,
    color: '#636368',
    opacity: 0.95,
  },
  activeTabIconContainer: {
    backgroundColor: '#1A1A1A',
    borderRadius: 20,
    width: 84,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeTabIconText: {
    fontSize: 32,
    color: '#FFF',
  },
  checkMarkCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    overflow: 'hidden',
    backgroundColor: '#95D097',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 4.5,
  },
  checkMarkEmpty: {
    backgroundColor: '#F0F0F0',
  },
  noStreakHolder: {
    backgroundColor: 'transparent',
  },
  checkMarkSad: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#999',
  },
  checkMarkText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  fireMarkCircle: {
    borderRadius: 17,
    backgroundColor: '#FFE9CB',
    borderWidth: 1,
    borderColor: '#FFD49B',
  },
  fireMarkText: {
    fontSize: 16,
  },
  fireEmoji: {
    fontSize: 16,
  },
  noStreakFace: {
    width: 27,
    height: 27,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noStreakRing: {
    position: 'absolute',
    width: 27,
    height: 27,
    borderRadius: 13.5,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#D6A03D',
  },
  noStreakEyesRow: {
    width: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: -2,
    marginBottom: 3,
  },
  noStreakEye: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#9E6324',
  },
  noStreakMouth: {
    width: 10,
    height: 3,
    borderRadius: 2,
    backgroundColor: '#8A531B',
  },
  sadText: {
    color: '#666',
    fontSize: 16,
  },
  bottomSheet: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 20,
    paddingBottom: 18,
    height: '84%',
  },
  streakBottomSheet: {
    height: '86%',
    backgroundColor: '#EFF1F4',
  },
  logBottomSheet: {
    height: '90%',
    backgroundColor: '#EFF1F4',
  },
  dragHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#DDD',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  sheetTitle: {
    fontSize: 31 / 2,
    fontWeight: '700',
    marginBottom: 20,
  },
  streakHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sheetTitleFire: {
    fontSize: 23,
    marginTop: -10,
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  monthLabel: {
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 10,
    marginTop: 6,
    color: '#2C2C31',
  },
  monthHistoryContainer: {
    paddingBottom: 8,
  },
  monthCard: {
    borderWidth: 1,
    borderColor: '#E8E8ED',
    borderRadius: 16,
    padding: 12,
    marginBottom: 12,
    backgroundColor: '#FBFBFD',
  },
  doneButtonBlack: {
    backgroundColor: '#0A0B0D',
    borderRadius: 28,
    paddingVertical: 14,
    marginTop: 8,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#F2A600',
    shadowColor: '#F2A600',
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  doneButtonText: {
    color: '#FFFFFF',
    fontSize: 28 / 2,
    fontWeight: '700',
  },
  logScrollContent: {
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 20,
  },
  logSurface: {
    flex: 1,
    marginHorizontal: 10,
    backgroundColor: '#EFF1F4',
    borderRadius: 30,
    overflow: 'hidden',
  },
  logHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 10,
  },
  backButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backArrow: {
    fontSize: 22,
    color: '#333',
  },
  logHeaderTitle: {
    fontSize: 34 / 2,
    fontWeight: '700',
  },
  kpBadge: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  tabRow: {
    flexDirection: 'row',
    backgroundColor: '#ECECF1',
    borderRadius: 13,
    padding: 4,
    marginBottom: 12,
  },
  toggleRow: {
    position: 'relative',
    flexDirection: 'row',
    borderRadius: 26,
    backgroundColor: '#D8DAE2',
    borderWidth: 2,
    borderColor: '#D0D3DA',
    paddingVertical: 5,
    paddingHorizontal: 8,
    marginBottom: 12,
    overflow: 'hidden',
  },
  togglePill: {
    position: 'absolute',
    top: 5,
    left: 8,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#0A0B0D',
    borderWidth: 2,
    borderColor: '#F2A600',
    shadowColor: '#F2A600',
    shadowOpacity: 0.35,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  toggleHalf: {
    flex: 1,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    paddingHorizontal: 4,
  },
  toggleText: {
    color: '#585E69',
    fontWeight: '600',
    fontSize: 15,
  },
  toggleTextActive: {
    color: '#FFFFFF',
  },
  activeTab: {
    flex: 1,
    backgroundColor: '#FFF',
    paddingVertical: 9,
    borderRadius: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  inactiveTab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
  },
  activeTabText: {
    fontWeight: '600',
    fontSize: 14,
  },
  inactiveTabText: {
    color: '#666',
    fontSize: 14,
  },
  dateSelectorRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#D8DAE2',
    borderRadius: 12,
    paddingVertical: 8,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#D0D3DA',
  },
  dateItem: {
    fontSize: 12,
    color: '#666',
    borderRightWidth: 1,
    borderColor: '#DDD',
    flex: 1,
    textAlign: 'center',
  },
  dateItemNoBorder: {
    fontSize: 12,
    color: '#666',
    flex: 1,
    textAlign: 'center',
  },
  formBlock: {
    flexDirection: 'row',
  },
  formRail: {
    width: 18,
    alignItems: 'center',
    paddingTop: 18,
  },
  railDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#8EC79B',
  },
  railLine: {
    width: 1,
    backgroundColor: '#A5D5AA',
  },
  railLineLong: {
    height: 96,
  },
  railLineMid: {
    height: 78,
  },
  formContent: {
    flex: 1,
    paddingLeft: 8,
  },
  inputLabel: {
    fontSize: 30 / 2,
    fontWeight: '600',
    marginBottom: 8,
    marginTop: 10,
  },
  optionalText: {
    fontWeight: '400',
    color: '#999',
  },
  dropdownInput: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#D8DAE2',
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#CFD3DA',
  },
  dropdownText: {
    fontSize: 14,
    color: '#333',
  },
  dropdownIcon: {
    color: '#666',
  },
  textAreaContainer: {
    backgroundColor: '#D8DAE2',
    borderRadius: 12,
    padding: 15,
    minHeight: 170,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#CFD3DA',
  },
  textArea: {
    fontSize: 32 / 2,
    color: '#333',
  },
  attachBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#F2A600',
    backgroundColor: '#0A0B0D',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 26,
    marginBottom: 15,
    shadowColor: '#F2A600',
    shadowOpacity: 0.35,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  attachIcon: {
    fontSize: 15,
    color: '#FFFFFF',
    marginRight: 8,
  },
  attachBtnText: {
    fontSize: 31 / 2,
    color: '#FFFFFF',
    flex: 1,
  },
  attachBtnIcon: {
    color: '#FFFFFF',
    fontSize: 16,
  },
  imagePreviewContainer: {
    position: 'relative',
    borderRadius: 12,
    overflow: 'hidden',
    height: 150,
    marginBottom: 20,
  },
  previewImage: {
    width: '100%',
    height: '100%',
  },
  removeImageBtn: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(250,250,252,0.92)',
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeImageText: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  coinBadge: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: '#F2E69D',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  coinText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#544E35',
  },
  bottomActionContainer: {
    paddingHorizontal: 18,
    paddingTop: 6,
    paddingBottom: 18,
    backgroundColor: '#EFF1F4',
  },
  mainActionButton: {
    backgroundColor: '#0A0B0D',
    paddingVertical: 14,
    borderRadius: 30,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#F2A600',
    shadowColor: '#F2A600',
    shadowOpacity: 0.35,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  mainActionText: {
    fontSize: 34 / 2,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  successOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.24)',
    alignItems: 'center',
    justifyContent: 'flex-end',
    zIndex: 30,
  },
  successCard: {
    width: '100%',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: '#FFFFFF',
    paddingTop: 74,
    paddingHorizontal: 24,
    paddingBottom: 34,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E7E3D8',
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
    overflow: 'visible',
  },
  successCloseButton: {
    position: 'absolute',
    top: 14,
    right: 14,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F3F4F7',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 3,
  },
  successBadgeLogo: {
    position: 'absolute',
    top: -44,
    alignSelf: 'center',
    width: 90,
    height: 90,
    shadowColor: '#C98D1C',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 8,
  },
  successTitle: {
    fontSize: 34 / 2,
    fontWeight: '800',
    color: '#15171A',
    textAlign: 'center',
    marginBottom: 10,
  },
  successSubtitle: {
    fontSize: 15,
    color: '#545A62',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 2,
  },
  streakCloseOverlay: {
    position: 'absolute',
    top: 0,
    height: 300,
    width: '100%',
  },
});

export default styles;
